[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
name = "lisp"
version = "0.1.0"
workspace = ".."

[dependencies]
nom = "3"
lazy_static = "0.2.8"
error-chain = "0.10"

[dependencies.cell-gc]
path = ".."

[dependencies.cell-gc-derive]
path = "../cell-gc-derive"

